-- Active: 1681927330654@@127.0.0.1@3306@eldenringdb
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Dragon', 'Ancient Dragon Lansseax', 'Dragon', 'Boss', 'ancientDragonLansseax.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Two Fingers', 'Blaidd the Half-Wolf', 'Shadowbound Beast', 'Warrior', 'blaiddTheHalfWolf.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Unknown', 'Demi-Human Boc', 'Demi-human', 'NPC', 'demiHumanBoc.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Brother Corhyn', 'Human', 'NPC', 'brotherCorhyn.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'D, Beholder of Death', 'Human', 'NPC', 'dBeholderOfDeath.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'D, Hunter of the Dead', 'Human', 'NPC', 'dHunterOfTheDead.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'House Hoslow', 'Diallos Hoslow', 'Human Tarnished', 'NPC', 'diallosHoslow.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Dragon', 'Dragonlord Placidusax', 'Dragon', 'Dragonlord', 'dragonlordPlacidusax.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Godrick the Grafted', 'Edgar', 'Human', 'Great Rune Bearer', 'edgar.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golder Order', 'Elden Beast', 'Unknown', 'Vassal of the Greater Will', 'eldenBeast.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Ever-Brilliant Goldmask', 'Tarnished', 'NPC', 'everBrilliantGoldmask.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Prince of Death', 'Fia, Deathbed Companion', 'Human Tarnished', 'NPC','fiaDeathbedCompanion.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Stormveil Castle', 'Gatekeeper Gostoc', 'Unknown', 'Merchant', 'gatekeeperGostoc.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Stormveil Castle', 'Godefroy the Grafted', 'Demigod', 'Unknown', 'godefroyTheGrafted.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Godfrey, First Elden Lord', 'Demigod Tarnished', 'First Elden Lord', 'godfreyFirstEldenLord.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Stormveil Castle', 'Godrick the Grafted', 'Demigod', 'Ruler of Stormveil Castle & Great Rune Bearer','godrickTheGrafted.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Godwyn the Golden', 'Demigod', 'Prince of Death', 'godwynTheGolden.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Godrick the Grafted', 'Irina of Morne', 'Human', 'NPC','irinaOfMorne.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Unknown', 'Iron Fist Alexander', 'Jar', 'NPC', 'ironFistAlexander.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Unknown', 'Jar-Bairn', 'Jar', 'NPC','jarBairn.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Stormveil Castle', 'Kenneth Haight', 'Human', 'NPC', 'kennethHaight.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Volcano Manor', 'Knight Bernahl', 'Human', 'NPC', 'knightBernahl.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Unknown', 'Latenna', 'Albinauric', 'NPC', 'latenna.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Three Fingers', 'Lightseeker Hyetta', 'Human', 'NPC', 'lightseekerHyetta.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Dragon', 'Lichdragon Fortissax', 'Dragon', 'Godwyn’s Protector', 'lichdragonFortissax.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Haligtree', 'Malenia, Blade of Miquella', 'Demigod Empyrean', 'Great Rune Bearer','maleniaBladeOfMiquella.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Maliketh, the Black Blade', 'Numen Empyrean', 'Great Rune Bearer','malikethTheBlackBlade.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Margit, the Fell Omen', 'Omen Demigod', 'Morgott alter ego', 'margitTheFellOmen.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'You', 'Melina, the Kindling Maiden', 'Unknown', 'Maiden','melinaTheKindlingMaiden.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Unknown', 'Millicent', 'Human', 'NPC','millicent.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Haligtree', 'Miquella of the Haligtree', 'Demigod Empyrean', 'NPC', 'miquellaOfTheHaligtree.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Wailing Church', 'Miriel, Pastor of Vows', 'Turtoise', 'Pastor', 'mirielPastorOfVows.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Formless Mother', 'Mohg, Lord of Blood', 'Omed Demigod', 'Great Rune Bearer', 'moghLordOfBlood.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Nepheli Loux', 'Human Tarnished', 'NPC','nepheliLoux.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Unknown', 'Patches', 'Human', 'NPC Merchant', 'patches.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Lunar Princess Ranni', 'Pidia, Carian Servant', 'Albinauric', 'Merchant', 'pidiaCarianServant.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Greater Will', 'Queen Marika the Eternal', 'Numen', 'Vessel for the Elden Ring & Divine sovereign of the Lands Between','queenMarikaTheEternal.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Golden Order', 'Radagon of the Golden Order', 'Unknown', 'Male half of Marika','radagonOfTheGoldenOrder.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Carian Royal Family', 'Lunar Princess Ranni', 'Demigod Empyrean', 'NPC','lunarPrincessRanni.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Academy of Raya Lucaria', 'Rennala, Queen of the Full Moon', 'Unknown', 'Governor of the Academy of Raya Lucaria & Great Rune Bearer','rennalaQueenOfTheFullMoon.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Roundtable Hold', 'Roderika', 'Human Tarnished', 'NPC','roderika.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Volcano Manor', 'Rya/Zorayas', 'Human/Snake', 'NPC','ryaZorayas.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Volcano Manor', 'Rykard, Lord of Blasphemy', 'Demigod', 'Great Rune Bearer','rykardLordOfBlasphemy.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'God of Rot', 'Sage Gowry', 'Kindred of Rot', 'NPC','sageGowry.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Lunar Princess Ranni', 'Preceptor Seluvis', 'Human', 'NPC Merchant','preceptorSeluvis.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Two Fingers', 'Sir Gideon Ofnir, the All-Knowing', 'Human Tarnished', 'NPC','sirGideonOfnir.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Raya Lucaria', 'Sorcerer Rogier', 'Human Tarnished', 'NPC','sorcererRogier.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Primeval current', 'Sorceress Sellen', 'Human', 'NPC Merchant','sorceressSellen.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Redmane Castle', 'Starscourge Radahn', 'Demigod', 'Great Rune Bearer','starscourgeRadahn.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Volcano Manor', 'Tanith', 'Human', 'NPC','tanith.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Raya Lucaria', 'Thops', 'Human', 'NPC','thops.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Lunar Princess Ranni', 'War Counselor Iji', 'Troll', 'NPC','warCounselorIji.jpg')
INSERT INTO characters (id_character, affiliation, name, race, role, url_image) VALUES (default, 'Mohg, Lord of Blood', 'White Mask Varré', 'Human Tarnished', 'NPC','whiteMaskVarre.jpg')